import { StyleSheet } from 'react-native';
import { colors, shadows, spacing } from '@/theme';

export const styles = StyleSheet.create({
  // Tout l'écran vit sur l'ivoire : plus de dégradé, plus de feuille.
  screen: { flex: 1, backgroundColor: colors.background },
  header: { position: 'relative' },
  // Filigrane d'empreinte : le logo en café presque transparent, qui déborde
  // légèrement du coin haut droit de l'écran.
  watermark: {
    position: 'absolute',
    top: -10,
    right: -14,
    opacity: 0.07,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: spacing.md,
  },
  headerTitle: {
    fontSize: 30,
    fontWeight: '800',
    letterSpacing: -0.5,
    color: colors.primaryDeep,
  },
  // Bouton rond des actions d'en-tête : voile café, icône encre café.
  archiveBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  archiveDot: {
    position: 'absolute',
    top: -4,
    right: -6,
    minWidth: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: colors.accent,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 3,
  },
  archiveDotText: { fontSize: 10, fontWeight: '800', color: colors.textOnAccent },
  freshTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: colors.text,
    paddingHorizontal: spacing.md,
    marginBottom: spacing.md,
  },
  freshRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    gap: spacing.md,
  },
  // Tuile crème au coin signature : compteur et avatars des matchs frais.
  freshTile: {
    width: 92,
    height: 92,
    borderRadius: 20,
    borderBottomRightRadius: 8,
    backgroundColor: colors.cardSolid,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
    ...shadows.card,
  },
  freshCounterText: { fontSize: 18, fontWeight: '800', color: colors.text },
  freshEmptyText: { flex: 1, fontSize: 16, color: colors.textMuted },
  freshListContent: { gap: spacing.md, paddingRight: spacing.md },
  freshAvatar: {
    width: 92,
    height: 92,
    borderRadius: 20,
    borderBottomRightRadius: 8,
  },
  freshAvatarFallback: {
    backgroundColor: colors.surface,
  },
  freshAvatarLetter: { color: colors.primaryDeep, fontSize: 30, fontWeight: '800' },
  totalRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.md,
    paddingTop: spacing.md,
    paddingBottom: spacing.sm,
  },
  totalText: { fontSize: 15, fontWeight: '600', color: colors.textMuted },
  refreshText: { fontSize: 15, fontWeight: '600', color: colors.accent },
  emptyIcon: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: colors.accent,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: colors.text,
    textAlign: 'center',
    marginTop: spacing.md,
  },
  emptyText: {
    fontSize: 15,
    color: colors.textMuted,
    textAlign: 'center',
    marginTop: spacing.sm,
    maxWidth: 300,
    lineHeight: 22,
  },
  emptyActions: {
    alignSelf: 'stretch',
    gap: spacing.sm,
    marginTop: spacing.lg,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm + 4,
    gap: spacing.md,
  },
  separator: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: colors.border,
    marginLeft: spacing.md + 54 + spacing.md,
  },
  avatarWrap: { width: 54, height: 54 },
  avatar: { width: 54, height: 54, borderRadius: 27 },
  avatarFallback: {
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarLetter: { color: '#fff', fontSize: 22, fontWeight: '700' },
  // Badge bleu superposé en bas à gauche de l'avatar, sur pastille du fond
  // pour rester net posé sur la photo.
  verifiedWrap: {
    position: 'absolute',
    bottom: -2,
    left: -2,
    backgroundColor: colors.background,
    borderRadius: 9,
  },
  rowBody: { flex: 1 },
  rowName: { fontSize: 17, fontWeight: '700', color: colors.text },
  rowPreview: { fontSize: 14, color: colors.textMuted, marginTop: 2 },
  rowPreviewUnread: { color: colors.text, fontWeight: '600' },
  rowMeta: { alignItems: 'flex-end', gap: 4 },
  rowTime: { fontSize: 13, color: colors.textMuted },
  badge: {
    minWidth: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: colors.accent,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 5,
  },
  badgeText: { color: colors.textOnAccent, fontSize: 12, fontWeight: '700' },
  endText: {
    textAlign: 'center',
    color: colors.textMuted,
    fontSize: 13,
    paddingVertical: spacing.lg,
  },
});
