import { StyleSheet } from 'react-native';
import { colors, shadows, sigCorner, spacing } from '@/theme';

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.background },
  // La hauteur (fonction de l'écran) est posée en ligne dans le rendu.
  headerGrad: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
  },
  safe: { flex: 1 },
  scroll: { flex: 1 },
  content: { paddingBottom: spacing.xl * 2, gap: spacing.md },
  band: {
    alignItems: 'center',
    paddingTop: spacing.lg,
    paddingBottom: spacing.sm,
    paddingHorizontal: spacing.md,
    gap: spacing.sm,
  },
  avatarWrap: { width: 130, height: 130 },
  avatar: {
    width: 130,
    height: 130,
    borderRadius: 65,
    borderWidth: 4,
    borderColor: colors.cardSolid,
    ...shadows.card,
  },
  avatarFallback: {
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cameraBadge: {
    position: 'absolute',
    right: 0,
    top: 0,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.cardSolid,
    alignItems: 'center',
    justifyContent: 'center',
    ...shadows.card,
  },
  // maxWidth + flexShrink : un très long prénom s'abrège au lieu de pousser
  // le badge certifié hors de l'écran.
  nameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    maxWidth: '100%',
    paddingHorizontal: spacing.md,
  },
  name: { fontSize: 26, fontWeight: '800', color: colors.primaryDeep, flexShrink: 1 },
  balance: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  balanceText: { fontSize: 18, fontWeight: '700', color: colors.text },
  editPill: {
    height: 44,
    paddingHorizontal: 24,
    borderRadius: 18,
    borderBottomRightRadius: 8,
    borderWidth: 1.5,
    borderColor: colors.border,
    backgroundColor: colors.cardSolid,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: spacing.xs,
  },
  editPillText: { fontSize: 15, fontWeight: '700', color: colors.primaryDeep },
  carousel: {
    paddingHorizontal: spacing.md,
    gap: spacing.sm,
  },
  // La largeur (fonction de l'écran) est posée en ligne dans le rendu.
  promo: {
    backgroundColor: colors.cardSolid,
    borderRadius: 24,
    borderBottomRightRadius: sigCorner,
    padding: 18,
    gap: spacing.sm,
    ...shadows.card,
  },
  promoIconRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  promoIconCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  promoTitle: { fontSize: 20, fontWeight: '700', color: colors.text },
  promoText: { fontSize: 14, lineHeight: 20, color: colors.textMuted },
  promoBtnWrap: { alignSelf: 'flex-start', marginTop: spacing.xs },
  promoBtn: {
    height: 44,
    paddingHorizontal: 20,
    borderRadius: 18,
    borderBottomRightRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  promoBtnText: { fontSize: 14, fontWeight: '700', color: '#ffffff' },
  dots: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 6,
    marginTop: -spacing.xs,
  },
  dot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: colors.border,
  },
  dotActive: {
    width: 18,
    backgroundColor: colors.accent,
  },
  menu: {
    marginHorizontal: spacing.md,
    gap: 0,
  },
  menuCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    backgroundColor: colors.cardSolid,
    borderRadius: 20,
    borderBottomRightRadius: 8,
    padding: 16,
    marginBottom: 12,
    ...shadows.card,
  },
  menuIconWash: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: colors.washFrom,
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuLabel: { flex: 1, fontSize: 17, fontWeight: '600', color: colors.text },
  menuDetail: { fontSize: 14, fontWeight: '600', color: colors.textMuted },
});
