import { StyleSheet } from 'react-native';
import { colors, radius, spacing } from '@/theme';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.background },
  intro: { alignItems: 'center', paddingHorizontal: spacing.lg, paddingTop: spacing.md, gap: 6 },
  introTitle: { fontSize: 22, fontWeight: '800', color: colors.text, marginTop: 4 },
  introText: {
    fontSize: 14,
    color: colors.textMuted,
    textAlign: 'center',
    lineHeight: 20,
  },
  form: { padding: spacing.md, gap: spacing.sm, marginTop: spacing.md },
  phoneRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    height: 54,
    borderRadius: radius.sm,
    borderWidth: 1.5,
    borderColor: colors.border,
    backgroundColor: colors.inputBg,
    paddingHorizontal: spacing.md,
  },
  phoneRowError: { borderColor: colors.danger },
  prefix: { fontSize: 16, fontWeight: '700', color: colors.text },
  phoneInput: { flex: 1, fontSize: 16, color: colors.text },
  footer: { padding: spacing.md, marginTop: 'auto', gap: spacing.sm },
  secure: { textAlign: 'center', fontSize: 12, color: colors.textMuted },
  doneWrap: {
    flex: 1,
    justifyContent: 'center',
    padding: spacing.lg,
    gap: spacing.sm,
    alignItems: 'center',
  },
  doneIcon: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: colors.accent,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.sm,
  },
  doneTitle: { fontSize: 24, fontWeight: '800', color: colors.primaryDeep },
  doneText: {
    fontSize: 15,
    color: colors.textMuted,
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: spacing.md,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(23,18,23,.6)',
    justifyContent: 'center',
    padding: spacing.lg,
  },
  modalCard: {
    backgroundColor: colors.cardSolid,
    borderRadius: radius.lg,
    padding: spacing.lg,
    gap: spacing.sm,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: colors.primaryDeep,
    textAlign: 'center',
  },
  modalText: {
    fontSize: 15,
    color: colors.textMuted,
    textAlign: 'center',
    lineHeight: 21,
    marginBottom: spacing.sm,
  },
});
