import { StyleSheet } from 'react-native';
import { colors, shadows, sigCorner, spacing } from '@/theme';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.background },
  container: { flex: 1 },
  content: { paddingBottom: spacing.xl },

  titleBlock: { paddingHorizontal: spacing.md, marginTop: spacing.md, gap: spacing.sm },
  title: {
    fontSize: 31,
    fontWeight: '800',
    color: colors.text,
    lineHeight: 38,
    letterSpacing: -0.5,
    marginTop: spacing.xs,
  },
  subtitle: { fontSize: 15, color: colors.textMuted, lineHeight: 22 },

  body: { paddingHorizontal: spacing.md, marginTop: spacing.lg, gap: spacing.sm },
  sectionLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.textMuted,
    marginTop: spacing.md,
    marginLeft: 4,
    marginBottom: 2,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  cardStack: { gap: spacing.sm },
  tileRow: { flexDirection: 'row', gap: spacing.sm },

  // Prénom : un grand champ nu, le trait dit la validité.
  nameBlock: { marginTop: spacing.md, gap: spacing.sm },
  nameField: {
    fontSize: 32,
    fontWeight: '700',
    color: colors.text,
    paddingVertical: spacing.sm,
    letterSpacing: -0.4,
  },
  nameHint: { fontSize: 13, color: colors.textMuted },

  // La roue occupe une carte blanche à elle seule.
  wheelCard: {
    backgroundColor: colors.cardSolid,
    borderRadius: 24,
    borderBottomRightRadius: sigCorner,
    overflow: 'hidden',
    paddingVertical: spacing.xs,
    ...shadows.card,
  },
  wheel: { alignSelf: 'stretch' },
  dateField: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    minHeight: 56,
    backgroundColor: colors.cardSolid,
    borderRadius: 20,
    borderBottomRightRadius: sigCorner,
    paddingHorizontal: spacing.md,
    borderWidth: 1.5,
    borderColor: colors.border,
    ...shadows.card,
  },
  dateValue: { flex: 1, fontSize: 17, color: colors.text, fontWeight: '600' },
  datePlaceholder: { flex: 1, fontSize: 17, color: colors.textMuted },
  ageRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    marginTop: spacing.md,
  },
  agePill: {
    backgroundColor: colors.accent,
    borderRadius: 16,
    borderBottomRightRadius: 6,
    paddingHorizontal: 14,
    paddingVertical: 6,
  },
  agePillText: { fontSize: 15, fontWeight: '800', color: colors.textOnAccent },
  ageDate: { fontSize: 15, color: colors.textMuted },

  searchField: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    minHeight: 56,
    backgroundColor: colors.cardSolid,
    borderRadius: 20,
    borderBottomRightRadius: sigCorner,
    paddingHorizontal: spacing.md,
    borderWidth: 1.5,
    borderColor: colors.border,
    ...shadows.card,
  },
  searchInput: { flex: 1, fontSize: 17, color: colors.text },
  cityCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    backgroundColor: colors.cardSolid,
    borderRadius: 20,
    borderBottomRightRadius: sigCorner,
    paddingHorizontal: spacing.md,
    paddingVertical: 12,
    ...shadows.card,
  },
  cityIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cityName: { fontSize: 16, fontWeight: '600', color: colors.text },
  cityHint: { fontSize: 13, color: colors.textMuted },
  cityDetected: { fontSize: 12, fontWeight: '700', color: colors.accent },

  note: { fontSize: 14, color: colors.textMuted, lineHeight: 20 },
  noteRow: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 2 },

  photoGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm },
  photoCell: {
    width: '31.5%',
    aspectRatio: 3 / 4,
    borderRadius: 20,
    borderBottomRightRadius: sigCorner,
    overflow: 'hidden',
    backgroundColor: colors.cardSolid,
  },
  photoImg: { width: '100%', height: '100%' },
  photoEmpty: { borderWidth: 1.5, borderColor: colors.border, borderStyle: 'dashed' },
  photoNext: { borderColor: colors.accent },
  photoEmptyPress: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  photoUploading: { fontSize: 22, fontWeight: '800', color: colors.accent },
  mainTag: {
    position: 'absolute',
    left: 6,
    bottom: 6,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    backgroundColor: 'rgba(0,0,0,.6)',
    borderRadius: 8,
    borderBottomRightRadius: 4,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  mainTagText: { fontSize: 10.5, fontWeight: '700', color: '#ffffff' },
  photoRemove: {
    position: 'absolute',
    top: 6,
    right: 6,
    width: 23,
    height: 23,
    borderRadius: 12,
    backgroundColor: 'rgba(0,0,0,.55)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  photoDots: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginTop: spacing.xs,
    paddingHorizontal: 2,
  },
  photoDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.border,
  },
  photoDotOn: { backgroundColor: colors.accent },

  heightCard: {
    backgroundColor: colors.cardSolid,
    borderRadius: 24,
    borderBottomRightRadius: sigCorner,
    borderWidth: 1.5,
    borderColor: colors.border,
    padding: spacing.md,
    gap: spacing.xs,
    ...shadows.card,
  },
  heightReadout: {
    flexDirection: 'row',
    alignItems: 'baseline',
    justifyContent: 'center',
    marginBottom: spacing.xs,
  },
  heightValue: {
    fontSize: 40,
    fontWeight: '800',
    color: colors.text,
    letterSpacing: -1,
    fontVariant: ['tabular-nums'],
  },
  heightUnit: { fontSize: 18, fontWeight: '600', color: colors.textMuted },
  heightClear: { marginLeft: spacing.md },
  heightClearText: { fontSize: 13, fontWeight: '700', color: colors.accent },
  heightBounds: { flexDirection: 'row', justifyContent: 'space-between' },
  heightBound: { fontSize: 12, color: colors.textMuted },

  inputCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    minHeight: 56,
    backgroundColor: colors.cardSolid,
    borderRadius: 20,
    borderBottomRightRadius: sigCorner,
    paddingHorizontal: spacing.md,
    borderWidth: 1.5,
    borderColor: colors.border,
    ...shadows.card,
  },
  inputCardField: { flex: 1, fontSize: 16, color: colors.text },

  chipWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm },

  interestHead: { flexDirection: 'row', marginBottom: spacing.xs },
  countPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: colors.cardSolid,
    borderRadius: 16,
    borderBottomRightRadius: 6,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  countPillDone: { backgroundColor: colors.success, borderColor: 'transparent' },
  countPillText: { fontSize: 13, fontWeight: '700', color: colors.textMuted },
  countPillDoneText: { fontSize: 13, fontWeight: '700', color: '#ffffff' },

  bioCard: {
    backgroundColor: colors.cardSolid,
    borderRadius: 24,
    borderBottomRightRadius: sigCorner,
    borderWidth: 1.5,
    borderColor: colors.border,
    padding: spacing.md,
    gap: spacing.sm,
    ...shadows.card,
  },
  bioField: {
    minHeight: 150,
    fontSize: 17,
    lineHeight: 24,
    color: colors.text,
  },
  bioFoot: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  bioTrack: {
    flex: 1,
    height: 3,
    borderRadius: 2,
    backgroundColor: colors.border,
    overflow: 'hidden',
  },
  bioFill: { height: '100%', borderRadius: 2, backgroundColor: colors.accent },
  bioCount: {
    fontSize: 12,
    color: colors.textMuted,
    fontVariant: ['tabular-nums'],
  },

  error: { color: colors.danger, fontSize: 14, textAlign: 'center' },
  footer: {
    paddingHorizontal: spacing.md,
    paddingTop: spacing.sm,
    paddingBottom: spacing.sm,
    gap: spacing.sm,
  },
  skipBtn: { alignSelf: 'center', paddingVertical: 6 },
  skipText: { fontSize: 15, fontWeight: '600', color: colors.textMuted },
});
