import { StyleSheet } from 'react-native';
import { colors, radius, spacing } from '@/theme';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.background },
  content: { padding: spacing.md, paddingTop: 0 },
  sectionCard: {
    backgroundColor: colors.card,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
  },
  switchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    paddingHorizontal: spacing.md,
    paddingVertical: 14,
    backgroundColor: colors.card,
  },
  switchRowIcon: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  switchRowLabel: { fontSize: 16, fontWeight: '600', color: colors.text },
  switchRowDetail: { fontSize: 12, color: colors.textMuted, marginTop: 1 },
  themeOption: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    backgroundColor: colors.card,
    borderRadius: radius.md,
    borderWidth: 1.5,
    borderColor: 'transparent',
    paddingHorizontal: spacing.md,
    paddingVertical: 13,
    marginBottom: spacing.sm,
  },
  themeOptionActive: { borderColor: colors.primary },
  themeOptionIcon: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  themeOptionLabel: { fontSize: 16, fontWeight: '700', color: colors.text },
  themeOptionDetail: { fontSize: 12, color: colors.textMuted, marginTop: 1 },
  themeHint: {
    fontSize: 12,
    color: colors.textMuted,
    lineHeight: 17,
    textAlign: 'center',
    marginTop: spacing.xs,
  },
  accountZone: {
    alignItems: 'center',
    gap: spacing.md,
    marginTop: spacing.xl,
    marginBottom: spacing.xl,
  },
  signOutLink: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.danger,
    textDecorationLine: 'underline',
  },
  deleteLink: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.danger,
    textDecorationLine: 'underline',
  },
  footer: {
    fontSize: 12,
    color: colors.textMuted,
    marginTop: spacing.sm,
  },
});
