import { StyleSheet } from 'react-native';
import { colors, isDark, radius, spacing } from '@/theme';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.background },
  content: { padding: spacing.md, paddingTop: spacing.xs },
  title: {
    fontSize: 26,
    fontWeight: '800',
    color: colors.text,
    lineHeight: 33,
  },
  subtitle: {
    fontSize: 15,
    color: colors.textMuted,
    lineHeight: 22,
    marginTop: spacing.sm,
  },
  sectionTitle: {
    fontSize: 19,
    fontWeight: '800',
    color: colors.accent,
    marginTop: spacing.lg,
    marginBottom: spacing.sm,
  },
  benefitRow: { flexDirection: 'row', gap: spacing.md },
  benefitIcon: {
    width: 44,
    height: 44,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  benefitIconGift: { backgroundColor: isDark ? 'rgba(22,163,74,.18)' : '#dcfce7' },
  benefitIconFriend: { backgroundColor: isDark ? 'rgba(197,111,164,.18)' : '#FAE6F0' },
  benefitBody: { flex: 1, gap: 3 },
  benefitTitle: { fontSize: 16, fontWeight: '800', color: colors.text, lineHeight: 22 },
  benefitText: { fontSize: 14, color: colors.textMuted, lineHeight: 20 },
  codeLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.text,
    marginTop: spacing.lg,
    marginBottom: spacing.xs,
  },
  codeBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingLeft: spacing.md,
    padding: 6,
    gap: spacing.sm,
  },
  codeText: {
    flex: 1,
    fontSize: 20,
    fontWeight: '800',
    letterSpacing: 3,
    color: colors.text,
  },
  copyBtn: {
    backgroundColor: colors.accent,
    borderRadius: radius.sm,
    paddingHorizontal: 18,
    paddingVertical: 11,
  },
  copyBtnText: { fontSize: 14, fontWeight: '800', color: colors.textOnAccent },
  paidLine: { fontSize: 13, color: colors.success, fontWeight: '600', marginTop: spacing.sm },
  faqLine: { fontSize: 14, color: colors.textMuted, marginTop: spacing.lg },
  faqLink: { color: colors.primary, fontWeight: '700', textDecorationLine: 'underline' },
  footer: { padding: spacing.md, paddingTop: spacing.sm },
});
