import { StyleSheet } from 'react-native';
import { colors, isDark, radius, spacing } from '@/theme';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.background },
  container: { flex: 1 },
  headerTitle: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  // Cible tactile minimale des commandes du bandeau : 44 points, la taille
  // recommandée par les deux plateformes.
  headerBtn: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerAvatar: { width: 38, height: 38, borderRadius: 19 },
  headerAvatarFallback: {
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerAvatarLetter: { color: '#fff', fontSize: 15, fontWeight: '700' },
  // Pastille du badge certifié, superposée en bas à gauche de l'avatar.
  headerBadge: {
    position: 'absolute',
    bottom: -2,
    left: -3,
    backgroundColor: colors.cardSolid,
    borderRadius: 9,
  },
  headerName: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.text,
    maxWidth: 200,
  },
  list: { padding: spacing.md, gap: 6, flexGrow: 1 },
  emptyText: {
    textAlign: 'center',
    color: colors.textMuted,
    marginTop: spacing.xl,
    fontSize: 15,
  },
  msgColMine: { alignSelf: 'flex-end', alignItems: 'flex-end', maxWidth: '78%' },
  msgColTheirs: { alignSelf: 'flex-start', alignItems: 'flex-start', maxWidth: '78%' },
  // Espace entre deux groupes de parole (6 de gap + 8 = 14).
  groupGap: { marginTop: 8 },
  dayRow: { alignItems: 'center', marginVertical: spacing.sm },
  // Pilule café translucide en clair, voile ivoire en sombre : texte ivoire.
  dayPill: {
    backgroundColor: isDark ? 'rgba(246,237,243,0.16)' : 'rgba(72,26,70,0.78)',
    color: '#F6EDF3',
    fontSize: 12,
    fontWeight: '600',
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: radius.full,
    overflow: 'hidden',
  },
  bubble: {
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  bubbleMine: {
    backgroundColor: colors.accent,
    borderBottomRightRadius: 6,
  },
  bubbleTheirs: {
    backgroundColor: colors.cardSolid,
    borderBottomLeftRadius: 6,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    alignSelf: 'flex-end',
    marginTop: 2,
  },
  metaTime: { fontSize: 11 },
  // Sur une photo ou une vidéo : petite pastille sombre en bas à droite.
  mediaMeta: {
    position: 'absolute',
    bottom: 9,
    right: 9,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    backgroundColor: 'rgba(0,0,0,0.35)',
    borderRadius: radius.full,
    paddingHorizontal: 7,
    paddingVertical: 2,
  },
  reactionsPill: {
    flexDirection: 'row',
    gap: 4,
    backgroundColor: colors.surface,
    borderRadius: radius.full,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 8,
    paddingVertical: 2,
    marginTop: -6,
    marginHorizontal: 6,
  },
  reactionText: { fontSize: 13 },
  statusText: {
    fontSize: 11,
    fontWeight: '600',
    color: colors.textMuted,
    marginTop: 2,
    marginRight: 4,
  },
  actionOverlay: {
    flex: 1,
    backgroundColor: 'rgba(23,18,23,.55)',
    justifyContent: 'flex-end',
    padding: spacing.md,
  },
  actionCard: {
    backgroundColor: colors.card,
    borderRadius: radius.lg,
    padding: spacing.md,
    gap: spacing.xs,
    marginBottom: spacing.lg,
  },
  emojiRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.xs,
    marginBottom: spacing.sm,
  },
  emojiBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emojiText: { fontSize: 24 },
  actionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingVertical: 12,
    paddingHorizontal: spacing.xs,
  },
  actionRowText: { fontSize: 16, color: colors.text },
  actionRowTextDanger: { fontSize: 16, color: colors.danger, fontWeight: '600' },
  bubbleText: { fontSize: 16, color: colors.text, lineHeight: 22 },
  // Barre de saisie posée directement sur le fond, sans bandeau.
  composer: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    gap: spacing.sm,
  },
  // Bandeau qui remplace le composeur quand le DM initial attend sa réponse.
  // Même gabarit que le composeur pour que la fin de l'écran ne saute pas.
  lockedNotice: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    backgroundColor: colors.surface,
  },
  lockedNoticeText: {
    flex: 1,
    fontSize: 13,
    lineHeight: 18,
    color: colors.textMuted,
  },
  input: {
    flex: 1,
    minHeight: 46,
    maxHeight: 120,
    borderRadius: radius.full,
    backgroundColor: colors.cardSolid,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
    paddingHorizontal: 18,
    paddingVertical: 12,
    fontSize: 15,
    color: colors.text,
  },
  sendBtn: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: colors.accent,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelBtn: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: colors.cardSolid,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  // Bandeau d'enregistrement : la pastille remplace le champ de saisie le
  // temps de la note vocale, la pastille rouge pulse tant que le micro tourne.
  recordingPill: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    minHeight: 46,
    borderRadius: 23,
    backgroundColor: colors.surface,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
  },
  recordingDotWrap: {
    width: 22,
    height: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  // Onde derrière la pastille : même rouge, elle s'évase et s'efface en rythme.
  recordingDotHalo: {
    position: 'absolute',
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: colors.danger,
  },
  recordingDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: colors.danger,
  },
  // Chiffres tabulaires : le minuteur ne tremble pas quand les secondes défilent.
  recordingTimer: {
    fontSize: 15,
    color: colors.text,
    fontWeight: '700',
    fontVariant: ['tabular-nums'],
  },
  recordingLabel: { flex: 1, fontSize: 14, color: colors.textMuted },
  voiceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingVertical: 2,
    minWidth: 120,
  },
  voiceText: { fontSize: 14, fontWeight: '600' },
  attachBtn: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: colors.cardSolid,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bubbleMedia: { padding: 3, backgroundColor: 'transparent', borderWidth: 0 },
  mediaBubble: {
    width: 210,
    height: 270,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
    overflow: 'hidden',
  },
  fullImageOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,.92)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  fullImage: { width: '100%', height: '85%' },
  // `top` est posé à l'exécution depuis l'inset haut : voir Chat.tsx.
  fullImageClose: {
    position: 'absolute',
    right: 20,
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255,255,255,.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
