import { StyleSheet } from 'react-native';
import { colors, isDark, radius, spacing } from '@/theme';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.background },
  scroll: { paddingBottom: spacing.xl },
  hero: {
    marginHorizontal: spacing.md,
    borderRadius: radius.lg,
    padding: spacing.lg,
    gap: spacing.sm,
  },
  heroTitle: {
    fontSize: 26,
    fontWeight: '800',
    letterSpacing: 1,
    color: colors.primaryDeep,
  },
  heroText: { fontSize: 14, color: colors.primaryDeep, lineHeight: 20, opacity: 0.85 },
  heroPill: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: colors.card,
    borderRadius: radius.full,
    paddingHorizontal: 14,
    paddingVertical: 7,
    marginTop: spacing.xs,
  },
  heroPillText: { fontSize: 14, fontWeight: '800', color: colors.primaryDeep },
  sheet: { padding: spacing.md, gap: spacing.sm },
  sectionLabel: {
    fontSize: 13,
    fontWeight: '800',
    color: colors.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    marginTop: spacing.md,
  },
  card: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    backgroundColor: colors.card,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.md,
  },
  cardFeatured: { borderColor: colors.accent, borderWidth: 2, paddingTop: spacing.lg },
  cardDone: { backgroundColor: colors.surface },
  cardIcon: {
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
  },
  // Écrin doré de la pièce : décliné par thème, le crème fixe restait un rond
  // clair en mode sombre.
  cardIconFeatured: { backgroundColor: isDark ? 'rgba(199, 150, 60, 0.18)' : '#F7EBD5' },
  cardBody: { flex: 1, gap: 2 },
  cardTitle: { fontSize: 16, fontWeight: '700', color: colors.text },
  cardText: { fontSize: 13, color: colors.textMuted, lineHeight: 18 },
  codeLine: { fontSize: 13, color: colors.textMuted, marginTop: 4 },
  code: { fontWeight: '800', color: colors.primary, letterSpacing: 1 },
  amountPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    minWidth: 62,
    justifyContent: 'center',
    backgroundColor: colors.surface,
    borderRadius: radius.full,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  amountText: { fontSize: 14, fontWeight: '800', color: colors.primaryDeep },
  badge: {
    position: 'absolute',
    top: -10,
    right: spacing.md,
    backgroundColor: colors.success,
    borderRadius: radius.full,
    paddingHorizontal: 10,
    paddingVertical: 3,
  },
  badgeText: { fontSize: 11, fontWeight: '800', color: '#ffffff' },
  sponsorBox: {
    backgroundColor: colors.card,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.md,
    gap: spacing.sm,
    marginTop: spacing.xs,
  },
  sponsorTitle: { fontSize: 16, fontWeight: '700', color: colors.text },
});
