-- Dowe : schéma initial (appliqué sur le projet sbsxgwdpdjxsrxcccwno le 2026-07-24)
create type public.gender as enum ('homme', 'femme');

create table public.cities (
  id smallint generated by default as identity primary key,
  name text not null unique,
  province text not null,
  is_active boolean not null default true
);

create table public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text check (display_name is null or char_length(display_name) between 1 and 50),
  birth_date date check (birth_date is null or birth_date <= (current_date - interval '18 years')),
  gender public.gender,
  looking_for public.gender,
  city_id smallint references public.cities(id),
  bio text default '' check (bio is null or char_length(bio) <= 500),
  age_min smallint not null default 18 check (age_min >= 18),
  age_max smallint not null default 99 check (age_max <= 120),
  is_onboarded boolean not null default false,
  is_banned boolean not null default false,
  last_active_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (age_min <= age_max)
);
create index profiles_feed_idx on public.profiles (city_id, gender, last_active_at desc) where is_onboarded and not is_banned;

create table public.photos (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(user_id) on delete cascade,
  storage_path text not null,
  position smallint not null default 0,
  created_at timestamptz not null default now()
);
create index photos_user_idx on public.photos (user_id, position);

create table public.swipes (
  swiper_id uuid not null references public.profiles(user_id) on delete cascade,
  target_id uuid not null references public.profiles(user_id) on delete cascade,
  liked boolean not null,
  created_at timestamptz not null default now(),
  primary key (swiper_id, target_id),
  check (swiper_id <> target_id)
);
create index swipes_likers_idx on public.swipes (target_id, swiper_id) where liked;
create index swipes_daily_count_idx on public.swipes (swiper_id, created_at) where liked;

create table public.matches (
  id uuid primary key default gen_random_uuid(),
  user_a uuid not null references public.profiles(user_id) on delete cascade,
  user_b uuid not null references public.profiles(user_id) on delete cascade,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (user_a, user_b),
  check (user_a < user_b)
);
create index matches_user_a_idx on public.matches (user_a) where is_active;
create index matches_user_b_idx on public.matches (user_b) where is_active;

create table public.messages (
  id bigint generated always as identity primary key,
  match_id uuid not null references public.matches(id) on delete cascade,
  sender_id uuid not null references public.profiles(user_id) on delete cascade,
  content text not null check (char_length(content) between 1 and 2000),
  created_at timestamptz not null default now(),
  read_at timestamptz
);
create index messages_match_idx on public.messages (match_id, id desc);

create table public.blocks (
  blocker_id uuid not null references public.profiles(user_id) on delete cascade,
  blocked_id uuid not null references public.profiles(user_id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (blocker_id, blocked_id),
  check (blocker_id <> blocked_id)
);
create index blocks_blocked_idx on public.blocks (blocked_id);

create table public.reports (
  id uuid primary key default gen_random_uuid(),
  reporter_id uuid not null references public.profiles(user_id) on delete cascade,
  reported_id uuid not null references public.profiles(user_id) on delete cascade,
  reason text not null check (reason in ('faux_profil','harcelement','contenu_inapproprie','arnaque','mineur','autre')),
  details text check (details is null or char_length(details) <= 1000),
  status text not null default 'pending' check (status in ('pending','reviewed','actioned')),
  created_at timestamptz not null default now()
);

create table public.entitlements (
  user_id uuid primary key references public.profiles(user_id) on delete cascade,
  is_premium boolean not null default false,
  product_id text,
  store text,
  expires_at timestamptz,
  updated_at timestamptz not null default now()
);

create table public.push_tokens (
  user_id uuid not null references public.profiles(user_id) on delete cascade,
  token text not null,
  updated_at timestamptz not null default now(),
  primary key (user_id, token)
);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  insert into public.profiles (user_id) values (new.id) on conflict do nothing;
  insert into public.entitlements (user_id) values (new.id) on conflict do nothing;
  return new;
end $$;
create trigger on_auth_user_created after insert on auth.users
  for each row execute function public.handle_new_user();

create or replace function public.set_updated_at()
returns trigger language plpgsql set search_path = '' as $$
begin
  new.updated_at := now();
  return new;
end $$;
create trigger profiles_updated_at before update on public.profiles
  for each row execute function public.set_updated_at();
