import { StyleSheet } from 'react-native';
import { colors, radius, shadows, sigCorner, spacing } from '@/theme';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.background },
  // Le contenu s'empile du haut : caméra, phrase d'action, puis la note. Le
  // vide restant tombe en bas de l'écran, jamais avant la zone de scan.
  body: {
    flex: 1,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.xs,
    gap: spacing.md,
  },
  cameraBox: {
    width: '100%',
    maxWidth: 420,
    alignSelf: 'center',
    aspectRatio: 1,
    borderRadius: 28,
    // Coin signature : la zone de scan est un objet Dowe, pas un cadre neutre.
    borderBottomRightRadius: sigCorner,
    overflow: 'hidden',
    backgroundColor: colors.surface,
    ...shadows.card,
  },
  camera: { flex: 1 },
  permissionBox: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.md,
    padding: spacing.lg,
  },
  permissionText: {
    fontSize: 16,
    color: colors.text,
    textAlign: 'center',
    lineHeight: 23,
  },
  // Phrase d'action : ce qu'il faut faire, dit en grand sous la caméra.
  lead: {
    fontSize: 20,
    fontWeight: '800',
    color: colors.primaryDeep,
    textAlign: 'center',
    letterSpacing: -0.3,
    marginTop: spacing.xs,
  },
  // La règle du paiement, en carte crème : lisible, jamais une note de bas de
  // page en corps 13.
  hintCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    backgroundColor: colors.cardSolid,
    borderRadius: 20,
    borderBottomRightRadius: 8,
    padding: spacing.md,
    ...shadows.card,
  },
  hintIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.washFrom,
    alignItems: 'center',
    justifyContent: 'center',
  },
  hintText: {
    flex: 1,
    fontSize: 15,
    color: colors.text,
    lineHeight: 22,
  },
  frame: {
    position: 'absolute',
    top: '18%',
    left: '18%',
    right: '18%',
    bottom: '18%',
  },
  corner: {
    position: 'absolute',
    width: 34,
    height: 34,
    borderColor: colors.accent,
  },
  cornerTL: { top: 0, left: 0, borderTopWidth: 4, borderLeftWidth: 4, borderTopLeftRadius: 10 },
  cornerTR: { top: 0, right: 0, borderTopWidth: 4, borderRightWidth: 4, borderTopRightRadius: 10 },
  cornerBL: { bottom: 0, left: 0, borderBottomWidth: 4, borderLeftWidth: 4, borderBottomLeftRadius: 10 },
  cornerBR: { bottom: 0, right: 0, borderBottomWidth: 4, borderRightWidth: 4, borderBottomRightRadius: 10 },
  result: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.lg,
    gap: spacing.sm,
  },
  resultGranted: { backgroundColor: colors.accent },
  onAccent: { color: colors.textOnAccent },
  resultDenied: { backgroundColor: colors.danger },
  // L'écran de paiement reste neutre : ni vert ni rouge, rien n'est tranché.
  resultPayment: { backgroundColor: colors.background },
  resultIcon: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.md,
  },
  resultTitle: {
    fontSize: 30,
    fontWeight: '800',
    color: colors.primaryDeep,
    textAlign: 'center',
  },
  resultName: {
    fontSize: 19,
    fontWeight: '700',
    color: colors.primaryDeep,
    textAlign: 'center',
  },
  resultText: {
    fontSize: 16,
    color: colors.primaryDeep,
    textAlign: 'center',
    lineHeight: 23,
    maxWidth: 320,
  },
  // Écran de paiement de l'entrée : mise en page de formulaire, pas de verdict.
  paymentSafe: { flex: 1, backgroundColor: colors.background },
  paymentContent: { padding: spacing.md, paddingBottom: spacing.lg },
  paymentHead: { alignItems: 'center', gap: 4, marginBottom: spacing.md },
  paymentIcon: {
    width: 84,
    height: 84,
    borderRadius: 42,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.sm,
  },
  paymentTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: colors.text,
    textAlign: 'center',
  },
  paymentName: {
    fontSize: 17,
    fontWeight: '700',
    color: colors.textMuted,
    textAlign: 'center',
  },
  paymentPrice: {
    fontSize: 32,
    fontWeight: '800',
    color: colors.primary,
    textAlign: 'center',
    marginVertical: spacing.xs,
  },
  paymentText: {
    fontSize: 15,
    color: colors.textMuted,
    textAlign: 'center',
    lineHeight: 22,
    maxWidth: 320,
  },
  group: {
    backgroundColor: colors.card,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    paddingHorizontal: spacing.md,
    paddingVertical: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  rowActive: { backgroundColor: colors.surface },
  rowLabel: { flex: 1, fontSize: 16, fontWeight: '600', color: colors.text },
  phoneRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    height: 54,
    borderRadius: radius.sm,
    borderWidth: 1.5,
    borderColor: colors.border,
    backgroundColor: colors.inputBg,
    paddingHorizontal: spacing.md,
    marginTop: spacing.md,
  },
  phoneRowError: { borderColor: colors.danger },
  prefix: { fontSize: 16, fontWeight: '700', color: colors.text },
  phoneInput: { flex: 1, fontSize: 16, color: colors.text },
  paymentHint: {
    fontSize: 14,
    color: colors.textMuted,
    lineHeight: 20,
    marginTop: spacing.sm,
  },
  paymentFooter: {
    padding: spacing.md,
    gap: spacing.sm,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.border,
  },
  resultActions: {
    alignSelf: 'stretch',
    gap: spacing.sm,
    marginTop: spacing.lg,
  },
});
