import { StyleSheet } from 'react-native';
import { colors, radius, shadows, spacing } from '@/theme';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.background },
  content: { padding: spacing.md, paddingTop: 0 },
  intro: {
    fontSize: 13,
    color: colors.textMuted,
    lineHeight: 18,
    marginBottom: spacing.md,
  },
  card: {
    backgroundColor: colors.card,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.md,
    marginBottom: spacing.md,
  },
  costBadge: {
    position: 'absolute',
    top: -11,
    right: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.full,
    paddingHorizontal: 10,
    paddingVertical: 3,
    zIndex: 1,
    elevation: 2,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 3,
    shadowOffset: { width: 0, height: 1 },
  },
  costBadgeText: { fontSize: 12, fontWeight: '800', color: colors.text },
  cardTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.text,
    marginBottom: spacing.sm,
  },
  rowBetween: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  // flexShrink : un libellé long passe à la ligne au lieu de pousser le
  // Switch hors de la carte sur les petits écrans.
  rowLabel: { fontSize: 16, fontWeight: '700', color: colors.text, flexShrink: 1 },
  rowValue: { fontSize: 14, fontWeight: '600', color: colors.primary, flexShrink: 1 },
  hint: { fontSize: 12, color: colors.textMuted, lineHeight: 17 },
  chipWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    alignItems: 'center',
  },
  checkChip: {
    borderWidth: 1.5,
    borderColor: colors.border,
    borderRadius: radius.full,
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  checkChipActive: { borderColor: colors.primary, backgroundColor: colors.surface },
  checkChipText: { fontSize: 14, fontWeight: '600', color: colors.text },
  chipBadge: {
    position: 'absolute',
    top: -5,
    right: -3,
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  noPrefPill: {
    borderRadius: radius.full,
    backgroundColor: colors.surface,
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  noPrefPillActive: { backgroundColor: colors.primary },
  noPrefText: { fontSize: 14, fontWeight: '700', color: colors.textMuted },
  // Ville : libellé et valeur rose sur la même ligne, comme la maquette.
  cityRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  cityValue: {
    flex: 1,
    fontSize: 15,
    fontWeight: '600',
    color: colors.accent,
  },
  verifiedLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flexShrink: 1,
  },
  // Cartes d'intention : icône + libellé, coche ronde posée sur le coin.
  goalCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    borderWidth: 1.5,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingHorizontal: 14,
    paddingVertical: 11,
    backgroundColor: colors.cardSolid,
  },
  goalCardActive: { borderColor: colors.accent, backgroundColor: colors.surface },
  goalCardText: { fontSize: 14, fontWeight: '700', color: colors.text },
  genderRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  genderItem: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  checkbox: {
    width: 26,
    height: 26,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxActive: { backgroundColor: colors.primary, borderColor: colors.primary },
  genderLabel: { fontSize: 16, fontWeight: '600', color: colors.textMuted },
  onlineLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    flexShrink: 1,
    minWidth: 0,
    paddingRight: spacing.sm,
  },
  onlineDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: colors.success,
    marginBottom: spacing.sm,
  },
  footerZone: {
    marginTop: spacing.sm,
    marginBottom: spacing.xl,
    justifyContent: 'center',
  },
  footerIdle: {
    textAlign: 'center',
    fontSize: 13,
    color: colors.textMuted,
    paddingVertical: spacing.md,
  },
  payBar: {
    backgroundColor: colors.card,
    padding: spacing.md,
    paddingBottom: spacing.lg,
    gap: spacing.sm,
    ...shadows.floating,
    shadowOffset: { width: 0, height: -6 },
  },
  payBarInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  payBarText: { fontSize: 13, fontWeight: '700', color: colors.text },
});
